### ISSUE TITLE
Try find toolchains in common places for settings

### ISSUE THREAD

**Issue by i582** [i582/vlang-idea#109]

**Comment by MohammadMD1383** [comment]
Also we can search the `PATH` for that

**Comment by i582** [comment]
> Also we can search the `PATH` for that

Do you mean to search it for folders named `v`? Sounds like a good idea.

**Comment by MohammadMD1383** [comment]
I meant trying to find the `v` executable in the directories listed in the `PATH`. because someone may name the toolchaing folder like `jd7@nO`😂
