### ISSUE TITLE
IndexOutOfBounds Exception in VlangEnterHandlerDelegate.postProcessEnter

### ISSUE THREAD

**Issue by IkeVoodoo** [i582/vlang-idea#189]
Where: [Line 27](https://github.com/i582/vlang-idea/blob/75a79195dfa2f65485820806498db50a933e7f81/src/main/kotlin/org/vlang/lang/completion/VlangEnterHandlerDelegate.kt#L27)

Stack trace: [Pastebin](https://pastebin.com/0NCq2ub9)

**Comment by i582** [comment]
Thanks for the report, this is already the second known bug of this handler, it will be reworked to alpha version.
