### ISSUE TITLE
IndexOutOfBounds Exception in VlangCompletionUtil$FunctionInsertHandler.handleInsertion

### ISSUE THREAD

**Issue by IkeVoodoo** [i582/vlang-idea#193]
Where: [Line 482](https://github.com/i582/vlang-idea/blob/75a79195dfa2f65485820806498db50a933e7f81/src/main/kotlin/org/vlang/lang/completion/VlangCompletionUtil.kt#L482)

Stack trace: [Pastebin](https://pastebin.com/J5pbvVkV)

**Comment by IkeVoodoo** [comment]
Testing fix in local build

**Comment by i582** [comment]
Oh, such exceptions related to Lexer (`LexerEditorHighlighter`) are known and they do not seem to be related to the code that you attach. This is a big problem with string interpolation, I'm trying to fix it.

**Comment by IkeVoodoo** [comment]
I seem to have fixed it by simply checking the offset for now, which seems to have fixed it.

Of course, there is most likely a better way to handle this, right?

**Comment by i582** [comment]
And please attach the code on which the bug is reproduced, by the way, this is a good habit when you create an issue :)

**Comment by i582** [comment]
> I seem to have fixed it by simply checking the offset for now, which seems to have fixed it.
> 
> Of course, there is most likely a better way to handle this, right?

Bump, can you attach the code on which the bug is reproduced?
