### ISSUE TITLE
Support fuzzy-search for auto completion

### ISSUE THREAD

**Issue by MohammadMD1383** [i582/vlang-idea#215]
e.g. typing `min` should also bring up a variable named `my_int`

**Comment by IkeVoodoo** [comment]
I will take care of this, could I be assigned?

**Comment by i582** [comment]
> I will take care of this, could I be assigned?

Yep

**Comment by i582** [comment]
It seems that this already works like this, perhaps this is a bug in a particular case.
Please attach a minimal example that reproduces the issue.

<img width="629" alt="Снимок экрана 2022-10-20 в 21 39 07" src="https://user-images.githubusercontent.com/51853996/197019794-d01370ed-9349-4d6f-96c4-b11f336a7114.png">

**Comment by i582** [comment]
It seems that it already works like this.
Please attach a minimal example that reproduces the issue.

<img width="630" alt="Снимок экрана 2022-10-20 в 21 44 21" src="https://user-images.githubusercontent.com/51853996/197020724-55d6307c-5c93-4ffc-b545-1b45736b9992.png">

**Comment by IkeVoodoo** [comment]
![image](https://user-images.githubusercontent.com/55694349/197020919-0ef22ca5-dc4a-4b23-b342-a4112c5cf40c.png)
Works for me, completions are messed up for some reason but yeah it works
