### ISSUE TITLE
Pressing enter inside `{...}` doesn't remove extra whitespace

### ISSUE THREAD

**Issue by MohammadMD1383** [i582/vlang-idea#216]
https://user-images.githubusercontent.com/69088224/196854603-675c46e9-84d6-4f1c-aff0-2b13710a730e.mp4

**Comment by i582** [comment]
Please re-check on the last commit, you have an old version of autocomplete for `match`

https://user-images.githubusercontent.com/51853996/197038146-36a4a137-417e-4431-aea8-b0997d77c1a5.mov
