### ISSUE TITLE
[SUGGESTION] add a button somewhere to choose the V installation is

### ISSUE THREAD

**Issue by IkeVoodoo** [i582/vlang-idea#217]
Possible use cases

A. Multiple installations
B. You had to reinstall V

**Comment by i582** [comment]
Perhaps I did not understand you, but there is already possibility to change the path to V

<img width="981" alt="Снимок экрана 2022-10-21 в 00 07 15" src="https://user-images.githubusercontent.com/51853996/197047495-487ebd9f-ae67-48cc-9fd8-d8558d404d77.png">

**Comment by IkeVoodoo** [comment]
Well, I am blind.

**Comment by i582** [comment]
Let's close the issue then?

**Comment by IkeVoodoo** [comment]
Yes, I'll open a separate issue for another problem I am facing.
