### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by IkeVoodoo** [i582/vlang-idea#220]
Where: [Line 486](https://github.com/i582/vlang-idea/blob/84d6a458c33eb9581f8f53f6f261f4418343e626/src/main/kotlin/org/vlang/lang/completion/VlangCompletionUtil.kt#L486)
Stack trace: [Pastebin](https://pastebin.com/XLsPpq3V)

I can try to fix this myself

**Comment by i582** [comment]
Of course, can you attach the code on which this exception occurred?

**Comment by IkeVoodoo** [comment]
Do you mean the full file?

**Comment by i582** [comment]
> Do you mean the full file?

Minimal example is better where an exception occurs of course, but the entire file is ok.

**Comment by IkeVoodoo** [comment]
```v
for socket. {
```

**Comment by IkeVoodoo** [comment]
Also please take a look at  #211
