### ISSUE TITLE
Inspections not updating

### ISSUE THREAD

**Issue by IkeVoodoo** [i582/vlang-idea#227]
It appears as if whenever I rebuild the plugin and update it in IntelliJ, it does not update inspections, they are literally missing, I don't see any errors, so I literally have no idea.

This is starting to affect my ability to contribute, so my priority right now is finding a solution for this

**Comment by i582** [comment]
Are checks enabled in the settings?

<img width="1094" alt="Снимок экрана 2022-10-21 в 13 09 52" src="https://user-images.githubusercontent.com/51853996/197159238-d6996c34-c994-4f62-a6d6-e632c6f06abd.png">

**Comment by i582** [comment]
Hm, in the settings there is no way to enable checks?

**Comment by IkeVoodoo** [comment]
Yep, everything I've added is missing

**Comment by i582** [comment]
Try clear `./build` folder and run again

**Comment by IkeVoodoo** [comment]
It works now, it just wasn't updating the output jar :/
