### ISSUE TITLE
Plugin not detecting V installation on windows

### ISSUE THREAD

**Issue by IkeVoodoo** [i582/vlang-idea#230]
![image](https://user-images.githubusercontent.com/55694349/197185564-c57d1135-56bd-41ea-8b8e-f2041909c535.png)

**Comment by i582** [comment]
Please check that your plugin is built from the commit https://github.com/i582/vlang-idea/commit/58ee2ff329955b9f3eb124a1d29a2f7c53149a84?

**Comment by IkeVoodoo** [comment]
It is built from the latest changes

**Comment by IkeVoodoo** [comment]
Well, it does seem as if git didn't add the changes... I'll try again in a different way

**Comment by IkeVoodoo** [comment]
Ah I forgot that you have to sync the fork for it to grab the changes, my bad

**Comment by i582** [comment]
> It is built from the latest changes

If the problem is still there, then please install this version and try again, then attach logs (Help | Open Log in Explorer)

[vlang-idea-0.0.1.zip](https://github.com/i582/vlang-idea/files/9838574/vlang-idea-0.0.1.zip)

**Comment by IkeVoodoo** [comment]
it is fixed, thanks.
