### ISSUE TITLE
The toolchain location always required to reconfigurate

### ISSUE THREAD

**Issue by X-X3** [i582/vlang-idea#244]
![Screenshot_20221101_115146](https://user-images.githubusercontent.com/116139277/199391444-f06dab9c-3178-44c8-ad3c-37d75ac12346.png)

**Comment by i582** [comment]
Hi
Can you please choose the path to V in the first field? The plugin usually tries to find where V is installed. If there are no options to choose from, then click on the button with 3 dots next to it and select the folder with V, this will configure all fields except the last one.
In the latter, you need to select the path to the modules, if you do not know what it is, leave the field empty.

**Comment by Danil42Russia** [comment]
> Hi Can you please choose the path to V in the first field? The plugin usually tries to find where V is installed. If there are no options to choose from, then click on the button with 3 dots next to it and select the folder with V, this will configure all fields except the last one. In the last, you need to select the path to the modules, if you do not know what it is, leave the field empty.

There seems to be a lack of highlighting that the field is mandatory.

**Comment by i582** [comment]
> I already configured correctly, and recognized toolchain rightly, but when you reopen settings, the toolchians path is empty just as up screenshot.

What version are you using? What commit did you build the plugin from?

**Comment by JalonSolov** [comment]
If I go to Settings -> Languages -> V and choose the correct directory for my V install, it is not remembered.  When I open the same settings again, it is reset to /usr/local/bin (which is nowhere close to where I have V).

This means I have to change the location every single time.
