### ISSUE TITLE
Unresolved reference 'it' 

### ISSUE THREAD

**Issue by X-X3** [i582/vlang-idea#250]
Keyword 'it' is not recognized correctly

**Comment by i582** [comment]
Please attach the code in which it is not defined? Could the plugin find the definition of the function that calls with `it`?

**Comment by i582** [comment]
Should work now:

<img width="527" alt="Screen Shot 2022-11-26 at 16 27 40" src="https://user-images.githubusercontent.com/51853996/204088955-f865d4a6-10a7-4609-8aa7-e5009fb2e397.png">
