### ISSUE TITLE
Can't find plugin in the marketplace

### ISSUE THREAD

**Issue by tintin10q** [i582/vlang-idea#256]
When I search vlang in the marketplace of pycharm I don't get any results. Additionally on the jetbrains page it says:

 Not compatible with the version of your running IDE (CLion 2022.2.3, PyCharm 2022.2.2)

**Comment by i582** [comment]
Hi
Thank you for your interest in the plugin, however it is currently in closed alpha testing and will be available to everyone as a beta version on January 1, 2023.

**Comment by tintin10q** [comment]
Thanks for letting me know. It might be a good idea to put this in your README.md 🙂

Is it a closed alpha?

**Comment by i582** [comment]
> Thanks for letting me know. It might be a good idea to put this in your README.md 🙂

Already 😉

<img width="912" alt="Снимок экрана 2022-11-24 в 21 26 23" src="https://user-images.githubusercontent.com/51853996/203839962-bbf160a7-fd73-4873-824f-672d3c47ed47.png">
