### ISSUE TITLE
Error then run project

### ISSUE THREAD

**Issue by Anivie** [i582/vlang-idea#281]
Then i try to running my project,it will have a error after build success:
`Can't run D:\IDEA_WorkSpace\V-Test\bin\main, file not found`
I can find a main.exe in the bin folder,and running it with command line,but idea can't running it.

Plugin and vlang toolchain is the latest version,idea is 2022.2.4 (Ultimate Edition),os version Windows 11 (10.0.22621.819)

**Comment by i582** [comment]
Hi
This is definitely a bug, will be fixed soon. Thank you for feedback!

**Comment by i582** [comment]
@Anivie please, try this build [Vlang-0.0.1-alpha.zip](https://github.com/i582/vlang-idea/files/10102505/Vlang-0.0.1-alpha.zip)

**Comment by Anivie** [comment]
> @Anivie please, try this build [Vlang-0.0.1-alpha.zip](https://github.com/i582/vlang-idea/files/10102505/Vlang-0.0.1-alpha.zip)

Ok，This version can work greatly.

**Comment by i582** [comment]
Great!
