### ISSUE TITLE
File not found when running main.v

### ISSUE THREAD

**Issue by danieldaeschle** [i582/vlang-idea#283]
![image](https://user-images.githubusercontent.com/30751516/204392687-abd31941-d05b-40d4-9725-d3b8bef04514.png)

On windows a file called main.exe will be generated. But the extension tries to start just `main`.

**Comment by 32ns** [comment]
[fixed binary name for run configuration for Windows](https://github.com/i582/vlang-idea/commit/da4bcf4046feeab5f35ba172d57dfe0626a8d814) 

@[i582](https://github.com/i582/vlang-idea/commits?author=i582)
i582 committed 14 hours ago

**Comment by i582** [comment]
Yes, this has already been fixed.

**Comment by i582** [comment]
See this comment: https://github.com/i582/vlang-idea/issues/281#issuecomment-1328808374
