### ISSUE TITLE
Error then using block annotation

### ISSUE THREAD

**Issue by Anivie** [i582/vlang-idea#286]
### Describe the bug

![动画](https://user-images.githubusercontent.com/88354708/205229969-f45df7cf-15fb-497f-9851-8971965c2ddd.gif)
Error then using block annotation

### Expected Behavior

Using block annotation

### Current Behavior

Block annotation will  include an Non-Selected areas.

### Reproduction Steps

Type code with:
```vlang
struct User {
	id   int
	name string
}

struct Repo {
	users []User
}

fn (r Repo) find_user_by_id(id int) !User {
	for user in r.users {
		if user.id == id {
			// V automatically wraps this into a result or option type
			return user
		}
	}
	return error('User ${id} not found')
}

// A version of the function using an optional
fn (r Repo) find_user_by_id2(id int) ?User {
	for user in r.users {
		if user.id == id {
			return user
		}
	}
	return none
}

fn main() {
	repo := Repo{
		users: [User{1, 'Andrew'}, User{2, 'Bob'}, User{10, 'Charles'}]
	}
	user := repo.find_user_by_id(10) or { // Option/Result types must be handled by `or` blocks
		println(err)
		return
	}
	println(user.id) // "10"
	println(user.name) // "Charles"

	user2 := repo.find_user_by_id2(10) or { return }
}
```
Double click to select the second line.
Ctrl+Shift+/(On Windows) to annotation it.

### Environment details (`v doctor` output)

OS: windows, Microsoft Windows 11 ��ͥ���İ� v22621 64 λ
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 7 5800H with Radeon Graphics
CC version: Error: exec failed (CreateProcess) with code 2: 系统找不到指定的文件。
 cmd: cc --version

getwd: C:\Users\anivi
vmodules: D:\V_Repository
vroot: C:\SDK\Vlang
vexe: C:\SDK\Vlang\v.exe
vexe mtime: 2022-12-02 05:31:19
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 73675dc.cbe64cb

Git version: git version 2.33.0.windows.2
Git vroot status: weekly.2022.47-32-gcbe64cb5
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 cb89a4fe

**Comment by i582** [comment]
Hi
The video you attached seems to have problems with the highlight, perhaps this is the reason for the bug, since I can not reproduce it.
If the bug is still reproducible for you, then reopen this issue.
Thanks for the feedback!
