### ISSUE TITLE
`sin6_family ` in `__offsetof(C.sockaddr_in6, sin6_family)` is not resolved

### ISSUE THREAD

**Issue by i582** [i582/vlang-idea#343]
### Describe the bug

.

### Expected Behavior

.

### Current Behavior

.

### Reproduction Steps

.

### Environment details (`v doctor` output)

.

### IDE Type (IDEA Community/Ultimate, GoLand, CLion, etc.)

.

**Comment by 32ns** [comment]
75ae2a328038a56b8cc42a08bd5f12436933cf78  Failure to compile,There is another question. I want to use v-cc msvc run. Can I add a running parameter
![image](https://user-images.githubusercontent.com/1725120/208416952-cb017735-9506-457b-90ca-70c5b700f805.png)

**Comment by i582** [comment]
@32ns Hi, please, try again with latest master. 
It is better to ask questions in [discussions](https://github.com/i582/vlang-idea/discussions), and create separate issues for problems.

To add `-cc msvc` open configuration settings:

<img width="469" alt="Снимок экрана 2022-12-19 в 23 14 24" src="https://user-images.githubusercontent.com/51853996/208502152-23a5c040-cab1-49a6-808b-e81d38e5d3bc.png">

and set `-cc msvc` in **"Build Arguments"** field:

<img width="1152" alt="Снимок экрана 2022-12-19 в 23 14 07" src="https://user-images.githubusercontent.com/51853996/208502112-b96862d1-6ac7-466e-bf61-206b70fd2f57.png">

**Comment by 32ns** [comment]
Problem solved, thank you very much

**Comment by i582** [comment]
> Problem solved, thank you very much

Cool!
