### ISSUE TITLE
Early releases

### ISSUE THREAD

**Issue by peterlerche** [i582/vlang-idea#42]
Hi,

Even though the plugin is in its early stages of development, would it be possible to have releases?

I have tried to use VSCode, but the VLS breaks on startup. So currently using IDEA without any syntax highlight. 
Thanks for the hard work;

**Comment by i582** [comment]
Hi

Now there is a list of things that will be more annoying than if the plugin did not exist at all, I'm just working on them, there are quite a few more, but I think it should not take very long. After that, despite the fact that much is not ready, it will be possible to try to release the first very early pre-alpha v0.0.0.0.0.0.1 :D

**Comment by i582** [comment]
> Hi,
> 
> Even though the plugin is in its early stages of development, would it be possible to have releases?
> 
> I have tried to use VSCode, but the VLS breaks on startup. So currently using IDEA without any syntax highlight. Thanks for the hard work;

Hi

Can you tell me what kind of project you are working on? Can you describe a list of things that would be useful to you in the first place? This will help me understand my priorities.

**Comment by peterlerche** [comment]
Hi, 

It is a backend system parsing text files and extracting context, saving the data in a DB. I could write this in another language, but V has just crept under my skin. When tooling becomes better, I see V replacing Go in my workplace. 

What is essential for me is general syntax highlight and error highlight.

**Comment by i582** [comment]
Hi

Thanks for the answer. Error highlighting is of course the most difficult, as it requires everything to work correctly, otherwise there will be a lot of false positives. However, I can provide highlighting, as well as various auto-completion and the go to the definition / find usages in the alpha version.

**Comment by peterlerche** [comment]
Hi,

That would be wonderful. 

I have noticed that you have been working hard on this project. 
Thank you for your hard work.

**Comment by i582** [comment]
I just have time now until the day I start a new job, I will try to do more during this time for the first release 😄

**Comment by peterlerche** [comment]
Hi,
I am amazed by your commitment.  
You will significantly impact developers who want to learn and enjoy V.

**Comment by i582** [comment]
Hi
I think you will help me a lot with testing the first versions. I'll be very grateful!

**Comment by peterlerche** [comment]
Hi,
I will do my best to give you positive feedback.... ;-)

**Comment by MohammadMD1383** [comment]
> Hi
> 
> Thanks for the answer. Error highlighting is of course the most difficult, as it requires everything to work correctly, otherwise there will be a lot of false positives. However, I can provide highlighting, as well as various auto-completion and the go to the definition / find usages in the alpha version.


I have an idea for that

You can compile the project silently in background and check there are any errors. V is fast enough for that.

**Comment by peterlerche** [comment]
Thanks, I will do background compiling.

**Comment by i582** [comment]
Hi

I scheduled the first alpha version for November 1st, I'll have less time now due to work, but I hope to finish all the general things by then. I planned the first beta release for January 1, 2023, then it will already be a full-fledged plugin for working with V.

**Comment by peterlerche** [comment]
Thanks for all the hard work.  I think that there are a lot of developers who are looking forward to the release.

**Comment by i582** [comment]
> Thanks for all the hard work. I think that there are a lot of developers who are looking forward to the release.

Hi
Alpha testing is already underway, you can join, write me mr.makhneff@gmail.com
