### ISSUE TITLE
Check if the module name matches the folders structure

### ISSUE THREAD

**Issue by i582** [i582/vlang-idea#5]
See https://github.com/vlang/v/blob/master/doc/docs.md#modules

**Comment by IkeVoodoo** [comment]
I would like to implement this; I do not know where to implement it.

**Comment by i582** [comment]
> I would like to implement this; I do not know where to implement it.

See how other inspections are done, you need to add a new one and register it in plugin.xml.

**Comment by IkeVoodoo** [comment]
@i582 I am stuck right now, I've added the following to plugin.xml

```xml
<localInspection language="vlang" groupPath="V"
                 groupName="Naming conventions" shortName="VlangModuleNamingConventionInspection"
                 displayName="Module naming convention"
                 enabledByDefault="true" level="ERROR"
                 implementationClass="org.vlang.ide.inspections.namingConventions.VlangModuleNamingConventionInspection"/>
```

Made the following inspection

```kt
class VlangModuleNamingConventionInspection : VlangNamingConventionInspectionBase() {

    override fun buildVisitor(holder: ProblemsHolder, isOnTheFly: Boolean): PsiElementVisitor {
        return object : VlangVisitor() {
            override fun visitModuleClause(o: VlangModuleClause) {
                holder.checkModuleName(o)
            }
        }
    }

}
```

And added the following check

```kt
protected fun ProblemsHolder.checkModuleName(named: VlangModuleClause) {
    val name = named.name

    val identifier = named.identifier ?: return

    registerProblem(
        identifier,
        "Module name doesn't match parent folder name.",
        ProblemHighlightType.ERROR, MODULE_NAME_FIX
    )
}
```

However, it seems as if it never gets called (Instantly registering the problem for debugging)

**Comment by i582** [comment]
Hi
Sorry for the delay, everything seems to be correct in your code and it should work, hmm.

**Comment by i582** [comment]
Let's create a PR and I'll try to run the code on my own?

**Comment by IkeVoodoo** [comment]
Yep, sorry for not replying I wasn't home!

**Comment by i582** [comment]
> Yep, sorry for not replying I wasn't home!

It seems that the inspection is working

<img width="501" alt="Снимок экрана 2022-10-19 в 20 15 01" src="https://user-images.githubusercontent.com/51853996/196747144-d8f1a528-76f5-4883-86af-31e7ef60e755.png">
